# Helm sets the namespace at apply time; disable the KICS "namespace undefined" query
# (matches chargate's own manifests).
# kics-scan disable=611ab018-c4aa-4ba2-b0f6-a448337509a6
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dunmir.serviceAccountName" . }}
  labels:
    {{- include "dunmir.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end -}}
